name: timecampus

services:
  cap:
    image: tiago2/cap:latest
    network_mode: host
    environment:
      ADMIN_KEY: ${CAP_ADMIN_KEY}
      REDIS_URL: redis://127.0.0.1:6379
      SERVER_HOSTNAME: 127.0.0.1
      CORS_ORIGIN: ${CAP_CORS_ORIGIN:-https://admin.timecampus.asia}
      RATELIMIT_IP_HEADER: x-forwarded-for
    restart: unless-stopped
